### ISSUE TITLE
The guidelines followed

### ISSUE THREAD

**Issue by minghongx** [themagicalmammal/MagicalCV#11]
Hi,

Where can I find the guidelines this template followed?

**Comment by themagicalmammal** [comment]
I suggest consulting your university's career center for guidance on creating a CV. However, I had the opportunity to work with a career/job counselor and CV expert from my university, the University of Leeds, to develop mine. While finding precise guidelines may be difficult, there are common patterns in CVs that you should follow. You can cross-reference your CV with the university's CV checker tool to ensure that it adheres to these patterns. Keep in mind that different universities may have style variations, but they will generally follow the same set of rules. I have provided this [link](https://careerweb.leeds.ac.uk/downloads/19/cvs) to some example CVs that follow these guidelines, but please note that they may be slightly outdated.
