### ISSUE TITLE
Package biblatex Warning: 'sorting' option to '\printbibliography' is no longer supported.

### ISSUE THREAD

**Issue by AlvinRolling** [themagicalmammal/MagicalCV#15]
The warning is generated, as `\sorting` is no longer supported, as reported in [this issue](https://github.com/plk/biblatex/issues/345) of biblatex

https://github.com/themagicalmammal/Resume/blob/df316bf46961b7a4f4b66c4fff4fcb8e35b93a8a/cv/publications.tex#L11-L19

An alternative way to do this is as follows.

```tex
\newrefcontext[sorting=ydnt]
\printbibliography[
heading=none
]
```

**Comment by themagicalmammal** [comment]
Can you raise a pr?

**Comment by themagicalmammal** [comment]
#17
