### ISSUE TITLE
repeated occurrence of Year in publication section

### ISSUE THREAD

**Issue by AlvinRolling** [themagicalmammal/MagicalCV#16]
The publication article looks as below in the `Resume.pdf`,
`Journal of Computer and System Sciences 81.8 (Dec. 2015) pp. 1479–1495. 2015`. The year field 2015 appeared twice.

While it's not stated what format is intended for this CV, it might be a good choice to avoid this duplication. One related discussion of this problem regarding `issuetitle` can be found [Here](https://tex.stackexchange.com/questions/504615/biblatex-separate-date-from-issue-date-behind-journal-title-no-parentheses), and the corresponding code is found here.

https://github.com/themagicalmammal/Resume/blob/df316bf46961b7a4f4b66c4fff4fcb8e35b93a8a/russell.cls#L799-L818

**Comment by themagicalmammal** [comment]
Can you raise a pr for this as well?

**Comment by AlvinRolling** [comment]
Please see PR #18.

Besides, you might need to update the generated **Resume.pdf** in the repo afterwards.

**Comment by themagicalmammal** [comment]
Yes, will do that.
