### ISSUE TITLE
Insert Image

### ISSUE THREAD

**Issue by AlexINSERM** [themagicalmammal/MagicalCV#5]
Hello and thank you for the template.

I would like to add a small image (e.g. QR code) on the first column. 
Using \begin{figure} I have the following error: 
`Not in outer par mode. \begin{figure}`
Could you please help me to solve this problem 
Thank you in advance
Alex

**Comment by themagicalmammal** [comment]
It uses a some old libraries which might be causing the issue. If you fix it lmk or send it here I will try to look into it.
