### ISSUE TITLE
Text color?

### ISSUE THREAD

**Issue by vanchipara** [themagicalmammal/MagicalCV#6]
Hey! Thanks for this template; it looks wonderful. I've been trying to make the entire text of the resume black to no avail. I'm sure I missed it, but how do I change the entire resume's color?

**Comment by themagicalmammal** [comment]
It called "awesome-purple" in MagicalCV.cls

**Comment by Vaibhav-3625** [comment]
Hi, I couldn't find awesome-purple anywhere in russell.cls. So how to change the resume text to black
