### ISSUE TITLE
Links are not defined for Github and Linkedin

### ISSUE THREAD

**Issue by tiagobluiz** [themagicalmammal/MagicalCV#9]
## Description
The links for the Github and Linkedin links are not defined, demanding the user to manually input the whole link, making the experience of these links inconsistent - for some you need the username (e.g.: gitlab, StackOverflow, twitter), and for others the whole link.

**Current Behaviour**
![current-beh-cv](https://user-images.githubusercontent.com/26139260/224442658-640fbdeb-2ae5-404a-82ea-f9bc5b76eae8.png)
Note that the full link is shown.

**Expected/Desired Behaviour**
![expected-beh-cv](https://user-images.githubusercontent.com/26139260/224442715-13273a37-a35d-44fb-889c-3d230a8f3384.png)
Only user names are used now, the link is generated automatically.

## Affected Lines
https://github.com/themagicalmammal/Resume/blob/6a4621952c65529b99a92f378f966427c810a648/russell.cls#L477
https://github.com/themagicalmammal/Resume/blob/6a4621952c65529b99a92f378f966427c810a648/russell.cls#L501

**Comment by themagicalmammal** [comment]
It's fixed now, I have updated the same with overleaf but the new one will take few days to get published (overleaf thing).
